# Generated by Django 5.1.4 on 2026-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_order_guest_email_order_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_wrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift_wrap',
            field=models.BooleanField(default=False),
        ),
    ]
