# Generated by Django 5.1.4 on 2026-09-12 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cartitem_gift_wrap_orderitem_gift_wrap'),
        ('products', '0026_bundleconfiguration_product_bundle_eligible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleCartItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('original_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.bundleoffer')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='accounts.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleCartProduct',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bundle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='accounts.bundlecartitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='bundlecartitem',
            name='products',
            field=models.ManyToManyField(related_name='bundle_cart_items', through='accounts.BundleCartProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='BundleOrderItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('original_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.bundleoffer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='accounts.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BundleOrderProduct',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bundle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='accounts.bundleorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='bundleorderitem',
            name='products',
            field=models.ManyToManyField(related_name='bundle_order_items', through='accounts.BundleOrderProduct', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='bundlecartproduct',
            constraint=models.UniqueConstraint(fields=('bundle_item', 'product'), name='unique_bundle_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='bundleorderproduct',
            constraint=models.UniqueConstraint(fields=('bundle_item', 'product'), name='unique_bundle_order_product'),
        ),
    ]
