# Generated by Django 5.1.4 on 2026-09-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_bundlecartitem_bundlecartproduct_and_more'),
        ('products', '0026_bundleconfiguration_product_bundle_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlecartitem',
            name='bundle_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.bundleoffer'),
        ),
    ]
