# Generated by Django 5.1.4 on 2026-09-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_bundlecartitem_bundle_offer'),
        ('products', '0027_bundlepackagingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlecartitem',
            name='packaging_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.bundlepackagingoption'),
        ),
        migrations.AddField(
            model_name='bundlecartitem',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bundleorderitem',
            name='packaging_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bundleorderitem',
            name='packaging_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.bundlepackagingoption'),
        ),
        migrations.AddField(
            model_name='bundleorderitem',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
