# Generated by Django 5.1.4 on 2026-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_order_order_date_idx_order_order_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('local_free', 'Free local delivery'), ('express', 'Express delivery'), ('next_day', 'Next day delivery')], default='', max_length=20),
        ),
    ]
