# Generated by Django 5.1.4 on 2026-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_order_delivery_distance_km_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Delivery charge applied when the order is below the free-delivery threshold.', max_digits=10, null=True),
        ),
    ]
