# Generated by Django 5.1.4 on 2026-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
