# Generated by Django 5.1.4 on 2026-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shippingaddress_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Delivery information', max_length=120)),
                ('summary', models.TextField(default='Delivery availability and timelines depend on your location and order details.')),
                ('details', models.TextField(default='Delivery timelines depend on your delivery area, order time, product availability, and weather. Orders outside our regular service area may require review; any additional delivery fee will be confirmed before acceptance.')),
            ],
            options={
                'verbose_name': 'delivery guideline',
                'verbose_name_plural': 'delivery guideline',
            },
        ),
    ]
