# Generated by Django 5.1.4 on 2026-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_deliveryguideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguideline',
            name='fee_review_notice',
            field=models.TextField(default='Any additional delivery fee will be decided by our team during review and shared with you before acceptance.'),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='outside_area_notice',
            field=models.TextField(default='Delivery and return terms may differ for orders outside our regular service area.'),
        ),
    ]
