# Generated by Django 5.1.4 on 2026-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deliveryguideline_fee_review_notice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_title', models.CharField(default='Returns', max_length=120)),
                ('return_summary', models.TextField(default='Please inspect your order when it is delivered and contact us if there is an issue.')),
                ('return_details', models.TextField(default='Product-specific return or replacement eligibility, time limits, and conditions are shown on each product page and apply to that item.')),
                ('refund_title', models.CharField(default='Refunds', max_length=120)),
                ('refund_summary', models.TextField(default='Approved refunds are issued to the original payment method where possible.')),
                ('refund_details', models.TextField(default='Contact our support team with your order details to request help with a refund.')),
                ('cancellation_policy', models.TextField(default='Contact our support team as soon as possible to request an order cancellation.')),
            ],
            options={
                'verbose_name': 'return and refund policy',
                'verbose_name_plural': 'return and refund policy',
            },
        ),
    ]
