# Generated by Django 5.1.4 on 2026-09-26 06:53

from django.db import migrations, models


def update_default_cancellation_policy(apps, schema_editor):
    policy_model = apps.get_model('home', 'ReturnRefundPolicy')
    policy_model.objects.filter(
        pk=1,
        cancellation_policy=(
            'Contact our support team as soon as possible to request an order cancellation.'
        ),
    ).update(
        cancellation_policy=(
            'Orders may be cancelled within 24 hours of placement, provided they have not been '
            'dispatched. Contact our support team to request cancellation.'
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_returnrefundpolicy'),
    ]

    operations = [
        migrations.RunPython(
            update_default_cancellation_policy,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='returnrefundpolicy',
            name='cancellation_policy',
            field=models.TextField(default='Orders may be cancelled within 24 hours of placement, provided they have not been dispatched. Contact our support team to request cancellation.'),
        ),
    ]
