# Generated by Django 5.1.4 on 2026-09-26 17:17

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_returnrefundpolicy_cancellation_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('code', django_countries.fields.CountryField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='shippingaddress',
                    name='zip_code',
                    field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian PIN code.', regex='^[1-9][0-9]{5}$')]),
                ),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='home.countrymodel')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.state'),
        ),
    ]
