# Generated by Django 5.1.4 on 2026-09-27 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_require_shipping_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguideline',
            name='delivery_charge_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Show a notice that delivery charges may apply below this order amount.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='express_delivery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='express_delivery_max_hours',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='express_delivery_min_hours',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='free_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Free local delivery radius, provided the customer city also matches.', max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='next_day_delivery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='operational_office_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='operational_office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='deliveryguideline',
            name='operational_office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
