# Generated by Django 5.1.4 on 2026-09-27 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_deliveryguideline_delivery_charge_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguideline',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=80, help_text='Delivery charge applied when the order is below the free-delivery threshold.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deliveryguideline',
            name='delivery_charge_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum post-discount order total for free delivery.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
