# Generated by Django 5.1.4 on 2026-09-27 11:29

import django.core.validators
from django.db import migrations, models


def populate_missing_delivery_threshold(apps, schema_editor):
    DeliveryGuideline = apps.get_model('home', 'DeliveryGuideline')
    DeliveryGuideline.objects.filter(
        delivery_charge_threshold__isnull=True,
    ).update(delivery_charge_threshold=500)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_deliveryguideline_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_missing_delivery_threshold,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='deliveryguideline',
            name='delivery_charge_threshold',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Minimum post-discount order total for free delivery (configurable).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
