# Generated by Django 5.1.4 on 2026-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_deliveryguideline_delivery_charge_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryguideline',
            name='details',
            field=models.TextField(default='Delivery timelines depend on your delivery area, order time, product availability, and weather. Orders to PIN codes outside the Standard Service Area are estimated to arrive within 4–6 days.'),
        ),
        migrations.AlterField(
            model_name='deliveryguideline',
            name='outside_area_notice',
            field=models.TextField(default='Orders to PIN codes outside the Standard Service Area are estimated to arrive within 4–6 days.'),
        ),
    ]
