# Generated by Django 5.1.4 on 2026-09-27 11:44

import django.core.validators
from django.db import migrations, models


def replace_default_cancellation_text(apps, schema_editor):
    ReturnRefundPolicy = apps.get_model('home', 'ReturnRefundPolicy')
    ReturnRefundPolicy.objects.filter(
        pk=1,
        cancellation_policy=(
            'Orders may be cancelled within 24 hours of placement, provided they have not been '
            'dispatched. Contact our support team to request cancellation.'
        ),
    ).update(
        cancellation_policy=(
            'Contact our support team as soon as possible to request an order cancellation.'
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_deliveryguideline_details_and_more'),
    ]

    operations = [
        migrations.RunPython(
            replace_default_cancellation_text,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='returnrefundpolicy',
            name='cancellation_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Number of hours after placement when customers may cancel an order.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='returnrefundpolicy',
            name='cancellation_policy',
            field=models.TextField(default='Contact our support team as soon as possible to request an order cancellation.'),
        ),
    ]
