# Generated by Django 5.1.4 on 2026-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d/'),
        ),
    ]
