# Generated by Django 5.1.4 on 2026-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.IntegerField(default=0, help_text='Original price before discount'),
        ),
    ]
