# Generated by Django 5.1.4 on 2026-08-30 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_marked_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDetails',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('policy', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
