# Generated by Django 5.1.4 on 2026-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_returndetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_wrap_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_wrap_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
