# Generated by Django 5.1.4 on 2026-09-12 05:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_gift_wrap_available_product_gift_wrap_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_products', models.PositiveIntegerField(default=6, help_text='Maximum number of different products a customer can put in one bundle.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_eligible',
            field=models.BooleanField(default=False, help_text='Allow this product to be selected in gifting bundles.'),
        ),
        migrations.CreateModel(
            name='BundleOffer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='bundles/banners/%Y/%m/%d/')),
                ('packaging_image', models.ImageField(blank=True, null=True, upload_to='bundles/packaging/%Y/%m/%d/')),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='bundle_offers', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
