# Generated by Django 5.1.4 on 2026-09-12 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_bundleconfiguration_product_bundle_eligible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePackagingOption',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sample_image', models.ImageField(upload_to='bundles/packaging-samples/%Y/%m/%d/')),
                ('price', models.PositiveIntegerField(default=0, help_text='Additional charge for this packaging per complete bundle.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
