# Generated by Django 5.1.4 on 2026-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_bundlepackagingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_catalog',
            field=models.BooleanField(default=True, help_text='Show this product in the normal product listings and search results.'),
        ),
    ]
