# Generated by Django 5.1.4 on 2026-09-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_returndetails_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndetails',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
    ]
