# Generated by Django 5.1.4 on 2026-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_returndetails_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='notify_on_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='restock_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
